#!/usr/bin/env python3
"""
Hook Installer for Hermes Git Sentinel.
Installs .git/hooks/pre-commit into any registered repository.
"""
import sys
import os
import stat
import argparse
from pathlib import Path

if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding='utf-8', errors='replace')
        sys.stderr.reconfigure(encoding='utf-8', errors='replace')
    except Exception:
        pass

PYTHON_EXE = "C:/Users/purnomo/AppData/Local/hermes/hermes-agent/venv/Scripts/python.exe"
SENTINEL_PY = "D:/Documents/GEMINI-X-HERMES/skills/hermes-git-sentinel/scripts/sentinel.py"

PRE_COMMIT_SCRIPT_TEMPLATE = f"""#!/bin/sh
# Hermes Git Sentinel - Automated Pre-Commit Quality Gate
# Generated by Hermes Agent Architecture

PYTHON_BIN="{PYTHON_EXE}"
SENTINEL_SCRIPT="{SENTINEL_PY}"

echo "\\033[94m[HERMES SENTINEL]\\033[0m Running pre-commit quality gate..."

if [ -f "$PYTHON_BIN" ]; then
    "$PYTHON_BIN" "$SENTINEL_SCRIPT" --staged
    EXIT_CODE=$?
else
    python3 "$SENTINEL_SCRIPT" --staged 2>/dev/null || python "$SENTINEL_SCRIPT" --staged
    EXIT_CODE=$?
fi

if [ $EXIT_CODE -ne 0 ]; then
    echo "\\033[91m[HERMES SENTINEL BLOCKED]\\033[0m Pre-commit check failed. Commit aborted."
    exit 1
fi

exit 0
"""


def install_git_hook(repo_path: Path | str) -> bool:
    """Installs the pre-commit hook into repo_path/.git/hooks/pre-commit."""
    repo = Path(repo_path).resolve()
    git_dir = repo / ".git"
    
    if not git_dir.exists():
        print(f"❌ Error: {repo} is not a valid Git repository (.git not found).")
        return False
        
    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    
    hook_file = hooks_dir / "pre-commit"
    
    # Backup existing hook if not created by hermes
    if hook_file.exists():
        content = hook_file.read_text(encoding="utf-8", errors="ignore")
        if "HERMES SENTINEL" not in content:
            backup_file = hooks_dir / "pre-commit.backup"
            hook_file.rename(backup_file)
            print(f"ℹ️  Existing pre-commit hook backed up to {backup_file.name}")
            
    hook_file.write_text(PRE_COMMIT_SCRIPT_TEMPLATE, encoding="utf-8", newline="\n")
    
    # Make executable on Unix/Git Bash
    try:
        current_stat = os.stat(hook_file)
        os.chmod(hook_file, current_stat.st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    except Exception:
        pass
        
    print(f"✅ Successfully installed Hermes Git Sentinel hook to {hook_file}")
    return True


def main():
    parser = argparse.ArgumentParser(description="Install Hermes Git Sentinel pre-commit hook")
    parser.add_argument("repo", nargs="?", default=".", help="Target repository directory (default: current directory)")
    args = parser.parse_args()
    
    target_repo = Path(args.repo).resolve()
    success = install_git_hook(target_repo)
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
